### ISSUE TITLE
Title Bar Styling

### ISSUE THREAD

**Issue by PaulBGD** [wix/react-native-controllers#1]
Currently there's no way to style the title bar from the defaults.
Some of the styling that could be included:
- Font weight
- Font color
- Background color

**Comment by talkol** [comment]
It's moving :) Will hopefully finish on Thu
There's already stuff to play with in the style branch

https://github.com/wix/react-native-controllers/commit/7059061374b074e26bf289b286fc731f7fa8d507
https://github.com/wix/react-native-controllers/commit/1a518823db93354a31304b6e8c7a9345a043bd91

Pass styles through the styles prop

**Comment by PaulBGD** [comment]
Looks nice, great work :)

**Comment by talkol** [comment]
Colors are now fully supported in the style branch with an example
https://github.com/wix/react-native-controllers/tree/style

I'm planning to add a whole bunch of styles, I'll merge the branches when finished

**Comment by talkol** [comment]
merged and released under 1.0.4
See https://github.com/wix/react-native-controllers#styling-navigation

**Comment by PaulBGD** [comment]
👍

**Comment by joemckie** [comment]
Thanks for all the work on the project - it's the best navigator I've used for RN as of yet! The only downside is that it seems impossible to change the style of the title... Is there any plan to add font styling to the navigation?

**Comment by DanielZlotin** [comment]
@joemckie #87
