### ISSUE TITLE
NavigationControllerIOS set new root component

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-controllers#10]
I ran into this use case while working towards converting my project. Looks like this isn't currently supported, but it shouldn't be too hard to implement. 

Thoughts?

**Comment by talkol** [comment]
hmm.. Not sure I understand

It is currently possible to make NavigationControllerIOS as the only root of your application. Just remove all the others in the example project. This will leave you with a single screen app (no tabs, no side menu) that will have a navigation stack (you will be able to push and pop). If we were to change the example index.ios.js to this, this would be the result: https://gist.github.com/talkol/d71f176bf49bfbf25d0e

It is also possible to change application roots in runtime. Meaning start with one root and then change to a different root. We currently have this use-case in our production app where we switch between login state and logged-in state. They both have different roots. The app starts with the login root, and after you login, it changes root to the tab bar root (logged in). We do this by simply calling `ControllerRegistry.setRootController('NewRoot');`. In version 1.1.0 we've even added animations to make this transition. See the 2nd parameter for setRootController.

Or did you mean something else entirely and I've misunderstood :) If this is the case, please give me an example use-case.

**Comment by Jpoliachik** [comment]
Sorry, I should have been more specific. My use case involves using the drawer to switch sections of the app. Since I would like to keep the existing Drawer / NavigationController structure intact, I only need to switch the controller at the root of the NavigationController - not the root of the entire app. 

With a `UINavigationController`, this can be accomplished with: 
`[navigationController setViewControllers:@[yourRootViewController] animated:NO];` 

I submitted a working pull request #12  for you to take a look at. Let me know what you think

**Comment by Jpoliachik** [comment]
Resolved with #12

**Comment by talkol** [comment]
also added this feature to https://github.com/wix/react-native-navigation
and added examples + readme to both projects
thanks!
