### ISSUE TITLE
Errors on reloading application

### ISSUE THREAD

**Issue by siwymilek** [wix/react-native-controllers#17]
Applications throws errors on every reload.
"Controllers: controller with id drawer is already registered. Make sure all of controller id's you use are unique."

**Comment by talkol** [comment]
Yes.. it's annoying as hell. It's not a production issue since we don't have these reloads in live apps, but it annoys the hell out of development.

I'll figure something out, and if not.. we can always move this error into the console.log so it doesn't show a red screen and breaks the dev flow

**Comment by aarongreenwald** [comment]
If you end up moving the error into a console.log statement, maybe you can do that only when built in debug mode? This way, if there's an actual bug with a controller being registered using an existing id, the error will throw in CI or QA and will more likely be caught before releasing into the wild.

**Comment by talkol** [comment]
As a temp hotfix, we've removed this error altogether in release 1.2.3
We will add complete unregister logic when controllers are dealloced and then we'll be able to bring back the error
Leaving this issue open as a reminder, but the error should go away for now (1.2.3)

**Comment by siwymilek** [comment]
@talkol can you bring back previous version? No it is much worse, now you have to reboot app on every change in your code. I'm getting warnings "Can only update mounted or mounting component. [...]" and setting state doesn't work.

**Comment by guyca** [comment]
@siwymilek We didn't encounter such behaviour in our apps or in the example project. Could you perhaps post an example project where we can reproduce the problems you're experiencing?
For now, you can just switch back to the previous version - 1.2.2.
Thanks

**Comment by talkol** [comment]
@siwymilek It was a little difficult without a way to reproduce your error, but I gave it a shot. I just released 1.2.4 hot fix that hopefully will fix the reload issues once and for all.

https://github.com/wix/react-native-controllers/commit/bc654802884afba148002cade7edfb94a0d253c2

Try it out tell me how it goes (`npm update` and make sure you get 1.2.4)
Thanks @artald for the clever fix idea

**Comment by Jpoliachik** [comment]
I'm experiencing an issue with reloading I believe is related. When I hot reload, the controller showing last (before reload) is loaded first. 

When running the `react-native-navigation` redux-example, Login, then try a hot-reload. It'll attempt to reload the `FirstTabScreen` initially, then it'll load `LoginScreen`. 

> 2016-03-21 10:25:03.963 [info][tid:com.facebook.React.JavaScript] Running application "example.FirstTabScreen" with appParams: {"rootTag":1,"initialProps":{"navigatorID":"in7znywbbwphc_nav0","screenInstanceID":"8yopyu5cglon4","navigatorEventID":"8yopyu5cglon4_events"}}. **DEV** === true, development-level warning are ON, performance optimizations are OFF
> 2016-03-21 10:25:03.984 [info][tid:com.facebook.React.JavaScript] Running application "example.LoginScreen" with appParams: {"rootTag":11,"initialProps":{"navigatorID":"d5j1ruh7gk1ds_nav","screenInstanceID":"74dcye7gsoc8w","navigatorEventID":"74dcye7gsoc8w_events"}}. **DEV** === true, development-level warning are ON, performance optimizations are OFF

While this isn't a production issue, it's also a large annoyance during development if you have async operations kicked off during `componentDidMount`

**Comment by talkol** [comment]
You are correct. I suspect it's an issue when changing roots. Looking into it.

In the regular example (non-redux) where we have the same root and we push a new screen and then do a reload, do you get the same problem?

btw - don't worry, the fact that it's not a production issue will not prevent us from fixing it! our guys are developing with this too and stuff like that is driving them nuts as well

**Comment by talkol** [comment]
@Jpoliachik ok, after lots of experimentation I think I have a workaround:
https://github.com/wix/react-native-controllers/commit/65cf2c997749f9e7a34dd4f91e22f2a19e1b6c97
released it under hotfix 1.2.5
can you please check if this resolves the reload issue?

There's still a small memory leak with replace root that we'll need to get to the bottom of, but the impact on you should be pretty minimal

**Comment by Jpoliachik** [comment]
Yup, that works! Thanks man.

**Comment by siwymilek** [comment]
@talkol still I got the problem. After reload project I can't set my state because according to react, it's not mounted.
![screenshot](https://new.shover.us/f/1AIMKN)

**Comment by talkol** [comment]
@siwymilek I don't think this is a bug.. I think you're doing updates too early before things are mounted

Let's narrow down which setState causes this (remark each of them and reload until you get less warnings). When we know which one causes the issue I'll help you find the best practice flow to update in the correct times. Btw - if you can post your project on github or an example that has this issues, I'll gladly take a look.

**Comment by siwymilek** [comment]
@talkol You are right. It is probably because I have registered redux store listener, but it shouldn't be forget on each reload?

**Comment by talkol** [comment]
@siwymilek Every time you reload, all your JS code runs again, so it will be forgotten and the redux listener will be re-registered. We still need to understand exactly what's causing your component to setState

**Comment by siwymilek** [comment]
@talkol I got issues if I would to setRootController asynchronous. Is even technically possible to do it?
here is example repo: https://github.com/siwymilek/rn-controller-example-app
