### ISSUE TITLE
How to disable press event on swiping?

### ISSUE THREAD

**Issue by siwymilek** [wix/react-native-controllers#18]
How to disable events on main controller component during pull side menu?
As you can see on the screenshot, a tile is pressed.
![Screenshot](http://i.imgur.com/DQT5GsW.jpg)

**Comment by talkol** [comment]
Interesting.. maybe when the swipe starts we'll automatically remove user interaction from the main content view controller?

@artald what do you think

**Comment by siwymilek** [comment]
I found another issue about side menu. If you want to use components like [swipeout](https://github.com/dancormier/react-native-swipeout) you have a problem, because both components keep swiping in the same time.
![Screen](http://i.imgur.com/g6RLsUm.png)

Best solution would be possibility to disable swiping and showing side menu manually.

@talkol what do you think?

**Comment by talkol** [comment]
@siwymilek I agree, let's add the option to disable swiping altogether in the config for the side menu.

I'll assign this to @gran33 and hopefully he could implement this on the native side. The summary of the features we want:
1. Config for the side menu to completely disable swipe to open and close.
2. When the side menu is open, all taps outside the side menu (on the main view controller) should be caught and not sent down and cause the side menu to close.

**Comment by gran33** [comment]
@siwymilek How did u add this `ListView` (or table view) to this screen/view? In which `.js` file? Code snippet will help to fix this gesture collisions.

**Comment by siwymilek** [comment]
@gran33 this is [swipeout component](https://github.com/dancormier/react-native-swipeout)

**Comment by talkol** [comment]
@siwymilek we've just released the latest versions of controllers and navigation with the ability to disable the open gesture completely in the side menu using a prop called `disableOpenGesture`

**Comment by DanielZlotin** [comment]
We need to export something along the lines of `cancelReactTouches`, which will be called by implementors to block touches from propagating to JS (while opening the side menu for example), blocking unexpected selection of views. We should also handle it on our end by calling this method from our own side menu.

**Comment by drorbiran** [comment]
woa-1697

**Comment by artald** [comment]
Fixed and available in version 2.1.2. Now when the side menu pan starts the touches will be canceled.

For 3rd party integrations there's a native function that can be used to cancel all touches on all controllers in `RCCManagerModule` called `cancelAllRCCViewControllerReactTouches`.
If necessary it can also be called from JS using `cancelAllReactTouches`.
