### ISSUE TITLE
Getting an error when show modal view controller

### ISSUE THREAD

**Issue by gran33** [wix/react-native-controllers#19]
Hey,
First, awesome project!

Got an error when I try to use the modal `viewController`.
Using the example project, I try to show modal view controller and in the **second** time I get this error:
![simulator screen shot 17 mar 2016 12 08 13 pm](https://cloud.githubusercontent.com/assets/1650967/13842895/49399c06-ec39-11e5-8981-d29b1380a95a.png)

Thanks in advance!

**Comment by talkol** [comment]
As a temp hotfix, we've removed this error altogether in release 1.2.3
We will add complete unregister logic when controllers are dealloced and then we'll be able to bring back the error
