### ISSUE TITLE
Some properties for tabBar

### ISSUE THREAD

**Issue by siwymilek** [wix/react-native-controllers#20]
Hey,
I have to set badge to tabBar item and change tilt color for icon? Is there any possibility?

**Comment by talkol** [comment]
Not yet. We're planning to add both features (we've focused so far on the nav bar styling, the tab bar is next :) ). I'll update this issue when we have something

**Comment by talkol** [comment]
Added on https://github.com/wix/react-native-controllers/commit/e54a3371adf33eced40c35980ba2d040864e9fc5

Will be included in the next release

**Comment by talkol** [comment]
released 1.2.6 with this inside
