### ISSUE TITLE
Add native dependencies as CocoaPod

### ISSUE THREAD

**Issue by adamski** [wix/react-native-controllers#22]
It would be useful to be able to install the native dependencies here via CocoaPods, for projects that are including React Native using CocoaPods.

**Comment by talkol** [comment]
good idea! is it something you know how to do?

**Comment by adamski** [comment]
I've been looking into it. Almost got a Podspec working. Only stumbling block is how to reference the React dependency, as the last version registered as a CocoaPod is 0.11.0 which is quite old now, and the Podspec in the RN master repo is `0.0.1-master` and since its not registered I can't reference it so it fails the `pod spec lint` command. 

Anyway I have raised an issue on the RN repo, and will see if I can work around it. Will submit a PR once its working.

**Comment by talkol** [comment]
:+1:  looking forward

**Comment by adamski** [comment]
See #24

**Comment by talkol** [comment]
Will integrate it on Thu

**Comment by adamski** [comment]
Any plans to integrate #24 soon?

**Comment by colinhang** [comment]
It would be nice to add pod dependency. When will #24 be integrated?

**Comment by drorbiran** [comment]
Hi all,
Wanted to update you that we decided that we are not going to address Podspec and CocoaPods at this stage.
