### ISSUE TITLE
When changing the root controller, the previous root is leaking until the next setRootController

### ISSUE THREAD

**Issue by artald** [wix/react-native-controllers#25]
When setting a new root using the `setRootController` action, the previously presented root is not dealloced until another root is set. 

_Example scenario:_
_\- the app starts with root A._
_\- the app sets a new root B. A is still not dealloced at this point._
_\- the app sets a new root C. A is now dealloced (but B isn't yet)._

**Comment by siwymilek** [comment]
Probably you mean [this issue](https://github.com/wix/react-native-controllers/issues/17)

**Comment by artald** [comment]
@siwymilek thanks. the leak is indeed mentioned there but this is a separate issue that needs to be taken care of.

**Comment by artald** [comment]
Fixed with [e02d1d5](https://github.com/wix/react-native-controllers/commit/e02d1d53b7359aacdb9ae8934dde8ec50b948cb7) and available in [release 1.3.3](https://github.com/wix/react-native-controllers/releases/tag/1.3.3)
