### ISSUE TITLE
Add support for multiple modals on top of eachother

### ISSUE THREAD

**Issue by talkol** [wix/react-native-controllers#26]
Right now we only support one modal at any given time

The API should remain the same, dismissModal should dismiss the topmost modal

**Comment by siwymilek** [comment]
@talkol what do you think to add passing props to modal?

**Comment by talkol** [comment]
@siwymilek that's a good point..

Currently the show modal is a very low level function that takes a controller and displays it. A controller doesn't accept props. It has its own JSX definition where we can pass props directly to its children. But that's not very convenient because this means you need to define JSX on the fly for every new modal you have if they each have different props.

That's actually what happens in https://github.com/wix/react-native-navigation
If you'll look at the docs you'll see that the react-native-navigation does allow you to send props to modals and that's exactly how it's implemented. Just a higher level of abstraction over the low level interface

I'm worried that adding props to the original low level function will complicate it.. what do you think? are you using controllers directly or through navigation?

**Comment by siwymilek** [comment]
@talkol I'm sorry but I don't understand what you mean of "using controllers directly or through navigation"

**Comment by talkol** [comment]
@siwymilek see this:
https://github.com/wix/react-native-controllers#before-you-start

"[react-native-controllers](https://github.com/wix/react-native-controllers) is a low-level package with API that wasn't designed to be cross-platform (since it's optimized for native UX). We have another project called [react-native-navigation](https://github.com/wix/react-native-navigation) which is a syntactic sugar wrapper around react-native-controllers. It provides the same native goodness with API that is much simpler, cross-platform between iOS and Android, and supports redux!"

I meant to ask if you're using react-native-controllers or the react-native-navigation wrapper

**Comment by siwymilek** [comment]
@talkol I use react-native-controllers

**Comment by talkol** [comment]
@artald added multiple modal support.
Leaving the issue open until we address @siwymilek request for props

**Comment by artald** [comment]
@talkol I think we should close this one and open a separate issue for the props. They are not related in any way.

**Comment by talkol** [comment]
Sure, @artal do you mind closing and opening a new issue?

**Comment by artald** [comment]
np.
Multiple modals closed with [ffdcda2](https://github.com/wix/react-native-controllers/commit/ffdcda25ce674e4c6ba0cbd86ea2122eadc682f2).
New issue for passing props to modal is [here](https://github.com/wix/react-native-controllers/issues/34).

**Comment by talkol** [comment]
@siwymilek the next release will include support for passing props to modals

**Comment by siwymilek** [comment]
@talkol ok, thanks for call :) By the way, could you answer for my last post on [Issue #17](https://github.com/wix/react-native-controllers/issues/17#issuecomment-203882824)?
