### ISSUE TITLE
Switch tabs through code

### ISSUE THREAD

**Issue by PaulBGD** [wix/react-native-controllers#27]
Is there a way to switch the tab in our code?

**Comment by talkol** [comment]
I'm planning a sprint on tabs, with full styling (changing colors), setting selected tab through code, adding badges over tabs (from the PR). Should be done in a day or two

**Comment by smooJitter** [comment]
How long would it be before we see these changes in react-native-navigation packages.

**Comment by PaulBGD** [comment]
@talkol Sounds great, as always great work!

**Comment by talkol** [comment]
Done. Added on https://github.com/wix/react-native-controllers/commit/e54a3371adf33eced40c35980ba2d040864e9fc5. Going to work on the README and immediately after that @smooJitter add all the stuff to react-native-navigation

**Comment by talkol** [comment]
notice I will only release the package with this stuff tomorrow after some qa

**Comment by talkol** [comment]
released 1.2.6 with this inside

**Comment by talkol** [comment]
@smooJitter all tab features (styles, switching, badges, toggle) are now available in react-native-navigation 0.1.5
