### ISSUE TITLE
rightButton to go to last popped screen?

### ISSUE THREAD

**Issue by adamski** [wix/react-native-controllers#33]
I don't know if this is possible, but I'd like to be able to go back to a popped screen:

My app starts with a list view screen, and a user can select an item which takes them to the next screen displaying the chosen detail view. I would like, when the user goes back to the list, for them to be able to return to the detail view without having to choose the same item again.

**Comment by talkol** [comment]
IMO this isn't a standard iOS feature, once a screen is popped it's released from memory.
If you want to implement this functionality you can do it manually in your business logic.. save the last item viewed and when they click to see the detail view again, just manually push this item again.

**Comment by talkol** [comment]
I'm closing the issue, please re-open if want to continue this discussion
