### ISSUE TITLE
setRootController with animation fails if this is the initial setRootController

### ISSUE THREAD

**Issue by talkol** [wix/react-native-controllers#41]
Assuming you only have one controller in your app, if you start it with `setRootController('MoviesApp', 'slide-down')`, the app doesn't start

**Comment by artald** [comment]
@talkol just pushed a fix (see [fea42c1](https://github.com/wix/react-native-controllers/commit/fea42c15f093b1a614cbdf85d9d1d25b3f3b701e)).
Please see that it solves the issue in your project, and if so - include it on the next release.

**Comment by talkol** [comment]
looks good. will release today
