### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by shanealsingh** [wix/react-native-controllers#48]
Hey!

I'm using the NavigationControllerIOS. I was wondering if there is a way to persist a sticky footer across all view that get pushed in? Any help would be much appreciated!

thanks!

**Comment by drorbiran** [comment]
Hey, we didn't quite understand your request.
Can you please open an issue in [react-native-navigation](https://github.com/wix/react-native-navigation) and add a screenshot/example of your request? 

Thanks!

**Comment by artald** [comment]
@drorbiran maybe this can be achieved using bottom in-app notification.
Not really a documented feature, see a reference here: https://github.com/wix/react-native-controllers/blob/c86f28c69a60385ce43c9a2cfb3d5cecd10ca3ef/index.js#L261

Examples are available in the example project
