### ISSUE TITLE
Toggle navigation bar

### ISSUE THREAD

**Issue by rmdort** [wix/react-native-controllers#49]
Is there any way to toggle Navigation bar programmatically?

I have a search bar below the navigation bar, When its in Focus, i would like to hide the nav bar.

**Comment by siwymilek** [comment]
👍

**Comment by gran33** [comment]
@rmdort @siwymilek 
Please see PR for your request:
https://github.com/wix/react-native-controllers/pull/54

`Toggle Navigation Bar option`
Enjoy

**Comment by rmdort** [comment]
Awesome. Thanks @gran33 . I was wondering should the api be similar to drawerController with `openNavBar`, `closeNavBar` and `toggleNavBar` ?

**Comment by gran33** [comment]
@rmdort Didn't merged to `master` yet, but the README is updated in the `hide_nav_bar` branch, see this:
https://github.com/wix/react-native-controllers/tree/hide_nav_bar#methods

**Comment by gran33** [comment]
@rmdort Pushed to master see release v1.3.6
