### ISSUE TITLE
Root view push tabbed view

### ISSUE THREAD

**Issue by adamski** [wix/react-native-controllers#52]
Just a heads up, I'm planning a PR to implement a custom TabController view that can be pushed from a root view. See http://www.wiredbob.com/2009/04/iphone-tweetie-style-navigation.html for an example of what I want to implement. I'm hoping to get onto this at the end of the coming week. 

Any thoughts / ideas welcome. 

Actually this could also be a question: Is it possible to animate setRootController to mimic pushing / popping a view? The back button can be faked easily enough. This would also meet my needs I think.

EDIT: I see that maybe all that is needed is left + right slide animation to be added in https://github.com/wix/react-native-controllers/blob/master/ios/RCCManagerModule.m#L117. Happy to work out a PR for this unless its easy for someone else to add.

**Comment by gran33** [comment]
Hi @adamski, is this issue still relevant?

**Comment by adamski** [comment]
No. I ended up using a [pure JS tab bar](https://github.com/alinz/react-native-tabbar) instead.
