### ISSUE TITLE
initial properties missing in RCCManager initBridgeWithBundleURL

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-controllers#55]
in our app we use RCTRootView like so

```
 RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
 moduleName:@"OurModuleName" //(irrlvnt with your navigator)
 initialProperties:@{ //(we want this params)
   @"isSimulator": @(isSimulator),
   @"isDebug": @(isDebug)}
 launchOptions:launchOptions];//(irrlvnt with your navigator)
```

this way, on our root.js component we have access to its props-> this.props.isSimulator will respond accordingly to the value that we have passed upon initialisation.
My question is: is there any way to pass these params?(or more) if no, can we make a pull request to fix this?

**Comment by edvinasbartkus** [comment]
I would add that current implementation/examples looses `launchOptions`. That means that initialURL and initialNotification are lost (`React.Linking.getInitialURL` and `React.PushNotificationIOS.popInitialNotification`).

**Comment by SergeyKorochansky** [comment]
Also bumped into this issue.

**Comment by simonmitchell** [comment]
Also bumped into this issue now.

**Comment by joeltrew** [comment]
Bumped into this issue

**Comment by DanielZlotin** [comment]
Fixed

**Comment by DanielZlotin** [comment]
@artald is this fixed?

**Comment by artald** [comment]
@DanielZlotin I think the push notifications issue is supposed to be fixed now as we are passing the launch options to the bridge when it's created.

However, these params are not passed to `RCTRootView` (I think we have a PR for this), so i'm not sure if there's a problem here.

Also, it's worth to check if our documentation and example project are up to date with the newer `RCCManager` initialization: `[[RCCManager sharedIntance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions]`

**Comment by DanielZlotin** [comment]
Alright so to summarise: we pass `launchOptions` to the bridge, but nothing other than that.
If any of you have any issues or fixes in mind, please open them in [navigation](https://github.com/wix/react-native-navigation/issues).
