### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by madvas** [wix/react-native-controllers#56]
So I cloned this repo.
- `cd examples`
- `npm install` (npm version 3.8.3)
- opened project in Xcode, hit the Run, build succeeded but simulator didn't open, nothing happened. 

Tried to restart Xcode, didn't help. 
Examples from [react-native-navigation](https://github.com/wix/react-native-navigation) are working fine.

Thank you

**Comment by siwymilek** [comment]
Any errors?

**Comment by madvas** [comment]
No, no errors. Just bunch of warnings, not sure if it's related.
![snap 2016-05-16 at 13 04 19 255x421](https://cloud.githubusercontent.com/assets/3857155/15287941/cc4edce4-1b66-11e6-8660-5f77e8381ae0.png)

**Comment by smooJitter** [comment]
I get the same warnings.  I also get yellow boxes regarding Deprecated use of react elements are created.

**Comment by madvas** [comment]
@smooJitter but does the simulator run for you?

**Comment by smooJitter** [comment]
Yes. It does.  This is the second post I've read about a blank screen though.  I haven't ran the example-redux it some time.  I started a project from scratch because I had issue with Xcode caching.

**Comment by gran33** [comment]
@madvas, is this issue still relevant?

**Comment by madvas** [comment]
I just let it go. We can close for now, maybe someone else who'll hit this issue, will reopen.
