### ISSUE TITLE
So if the drawer is set to "theSideBar", I cannot swipe to open it?

### ISSUE THREAD

**Issue by JO-WTF** [wix/react-native-controllers#57]
I tried to set the drawer type to "theSideBar" and use "airbnb" animation type. But I cannot swipe it to open and I didn't find any options to make it work.

Is it designed so?

Thanks.

**Comment by gran33** [comment]
Hi @JO-WTF, the drawer type of `theSideBar` isn't support swipe gestures, only open/close operations.
