### ISSUE TITLE
iOS 7 Compatibility

### ISSUE THREAD

**Issue by adamski** [wix/react-native-controllers#69]
I'm getting an error on running my app on device.

```
[RCCNavigationController setHidesBarsOnSwipe:]: unrecognized selector sent to instance
```

I can't find the reference to setHidesBarsOnSwipe anywhere - could this be getting called by iOS? 

iPhone 4, iOS v 7.1.2

**Comment by adamski** [comment]
Ah it seems this is because its part of iOS 8. http://stackoverflow.com/questions/28113849/ios-swift-uinavigationcontroller-hidesbarsonswipe-error
Any chance we can make this compatible with 7?

**Comment by adamski** [comment]
There are also 2 classes used that are not available on iOS 7: `UIBlurEffect` and `UIVisualEffectView`

**Comment by drorbiran** [comment]
Hi
We appreciate your pull request, but at this stage, we are not going to adress iOS 7 compability.
Thanks.

**Comment by adamski** [comment]
Ok, will it be something you will consider addressing when merging with react-native-navigation?

**Comment by drorbiran** [comment]
It's currently not a part of our road map.

**Comment by adamski** [comment]
Seems a shame, as its minimal code changes and has no impact on later iOS versions (that I am aware of) - I am targeting iOS 7 as a minimum in my app, same as React Native.

**Comment by DanielZlotin** [comment]
This is targeting less than 3% of the iOS devices in the world (which means less then 1.5% total), and will cost us more development time (also each feature will have to pass QA on 1 more device). Furthermore we will have iOS 10 soon, which means it will drop even further. We have to make compromises for our fast velocity and I think this is a no brainer. Same goes to supporting Android below api15.. Just too little market share to make it worth our time and resources.

**Comment by adamski** [comment]
Fair enough, I understand your position. Thanks for taking the time to explain.
