### ISSUE TITLE
Styling Tab Bar - tint overrides background color

### ISSUE THREAD

**Issue by schmoove** [wix/react-native-controllers#76]
Have I missed something, or is the iOS tint effect overriding the value entered for "tabBarBackgroundColor"?
# cc0000 is rendered as #bf1212
# ffffff is rendered as #ebebeb

Trying to set the background to absolute white, but always rendering grey.

**Comment by drorbiran** [comment]
This issue will be addressed to in react-native-navigation [#248](https://github.com/wix/react-native-navigation/issues/248)
