### ISSUE TITLE
Initially hidden tab bar?

### ISSUE THREAD

**Issue by aksonov** [wix/react-native-controllers#79]
My app uses drawer that is actually tabbar without visible tabs - so user may switch between these tabs using drawer, not tabbar. How to achieve that? I've tried to put TabBar inside NavBar with tabBarHidden style, but looks like NavBar allows only 'component', not inner TabBar (that is pity).

**Comment by aksonov** [comment]
Is this project alive??

**Comment by drorbiran** [comment]
Hi
We will address this issue in react-native-navigation [#249](https://github.com/wix/react-native-navigation/issues/249)
