### ISSUE TITLE
UINavigationBar right title and icon

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-controllers#8]
Are there any plans to support this? Any reasons this isn't supported already? 

Just checking before I start implementing myself. I think it should behave similarly to `setLeftButton`

**Comment by talkol** [comment]
Yes, of course. I actually did a complete overhaul of the button system - more than one button on each side, icon buttons and not only text buttons.

It's currently in a branch:
https://github.com/wix/react-native-controllers/tree/buttons

Will merge it to master in a couple of days, but you can use it now. It's already in the example project in the branch.

**Comment by Jpoliachik** [comment]
Nice! You rock.

**Comment by talkol** [comment]
Merged into master and released in 1.1.0
This cool release also includes modals and lightboxes
Documentation and example projects are updated
