### ISSUE TITLE
Ability to intercept the back button

### ISSUE THREAD

**Issue by lprhodes** [wix/react-native-controllers#84]
This would allow the back button to be intercepted in case you wish to perform some kind of action (e.g. a save) before leaving the view.

I've implemented in RNC and RNN, I would create a pull request but from the sounds of it you're refactoring a lot of that kind of code - it's here if anyone needs it though.

https://github.com/lprhodes/react-native-controllers/commit/d071f83901dd9cadb8da26bfa19217a72c7ef5b1
https://github.com/lprhodes/react-native-navigation/commit/d65b679c0b4183b80e532d80985ce0ce6685ff35

**Comment by drorbiran** [comment]
Hi
It's better if we will address this issue in react-native-navigation.
I have opened the the following issue [#250](https://github.com/wix/react-native-navigation/issues/250)
