### ISSUE TITLE
Customise RCTRootView background colour

### ISSUE THREAD

**Issue by joe-noel-dev** [wix/react-native-controllers#88]
Originally raised in wix/react-native-navigation#138, but I believe it is more appropriate in this repo.

React Native allows you to customise the background colour of the root view on iOS by doing something along the lines of `rootView.backgroundColor = [UIColor redColor];` in your AppDelegate.m. When using react-native-controllers however, this takes care of creating the root view so you never have access to it.

In my project, this means that the background colour of the root view is wrong, so when I navigate to a new route there is a flash of the wrong colour before my JS is loaded.

Is it possible to expose the default background property of the root view?

**Comment by littlesome** [comment]
+1, need this too

**Comment by drorbiran** [comment]
Hi
It will be addressed to in react-native-navigation
