### ISSUE TITLE
RCCViewController onRNReload bug

### ISSUE THREAD

**Issue by littlesome** [wix/react-native-controllers#93]
hi, I find this bug, which may cause onCancelReactTouches to crash after a Reload:

https://github.com/wix/react-native-controllers/blob/master/ios/RCCViewController.m#L163

```
-(void)onRNReload
{
    [[NSNotificationCenter defaultCenter] removeObserver:self.view];
    self.view = nil;
}
```

should be:

```
-(void)onRNReload
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    self.view = nil;
}
```

**Comment by littlesome** [comment]
More about my crash,

I'm on RN-0.30.0, and I have a left drawer, after a reload, try to open the drawer using gesture I got this:

```
-(void)onCancelReactTouches
{
  [(RCTRootView*)self.view cancelTouches];
}
```

self.view here is a UIView, not a RCTRootView, very strange, dont know why this happen, but the code above just fix this.

**Comment by aksonov** [comment]
I've fixed it in my fork, please check

Pavel.

**Comment by artald** [comment]
Thanks for reporting @littlesome we'll take a look
