### ISSUE TITLE
switchToTab does not work

### ISSUE THREAD

**Issue by edvinasbartkus** [wix/react-native-controllers#95]
I am aware that migration process is happening.
However, recent commits/changes have introduced a bug that breaks `.switchToTab({ tabIndex: x })`. 

What I could find that `platformSpecific.ios.js` in method `navigatorSwitchToTab` when receiving `navigator` object has attribute `navigatorID == undefined` resulting in failure to find `${navigatorID}_tabs` component in iOS code.

**Comment by DanielZlotin** [comment]
Please open all issues / pull requests in `react-native-navigation`, I'll fix it asap
